# Generated by Django 2.0.7 on 2018-07-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_invco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='invco',
        ),
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
