# Generated by Django 2.0.7 on 2018-07-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20180725_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatetedate', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
