# Generated by Django 2.0.7 on 2018-07-29 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
