# Generated by Django 2.0.7 on 2018-08-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20180801_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='street',
        ),
    ]
